steps:
- id: restoreCache
  name: gcr.io/$PROJECT_ID/restore_cache:latest
  args:
  - "--bucket=gs://$_COMPILE_CACHE_BUCKET"
  - "--key=$_IMAGE_NAME-$_BRANCH_NAME"
- id: buildCompileImage
  waitFor: ["restoreCache"]
  name: gcr.io/kaniko-project/executor
  args:
  - "--cache=true",
  - "--dockerfile=Dockerfile.compile",
  - "--destination=$_DOCKER_REGISTRY/compile-$_IMAGE_NAME:$_BRANCH_NAME"
- id: compile
  waitFor: ["buildCompileImage"]
  name: $_DOCKER_REGISTRY/compile-$_IMAGE_NAME:$_BRANCH_TAG
- id: buildSlimImage
  waitFor: ["compile"]
  name: gcr.io/kaniko-project/executor
  args:
  - "--cache=true",
  - "--dockerfile=Dockerfile.slim",
  - "--destination=$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME",
  - "--destination=$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-slim",
  - "--destination=$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$TAG_NAME",
  - "--destination=$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$TAG_NAME-slim",
- id: buildUbuntuImage
  waitFor: ["compile"]
  name: gcr.io/kaniko-project/executor
  args:
  - "--cache=true",
  - "--dockerfile=Dockerfile.ubuntu",
  - "--destination=$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-ubuntu",
  - "--destination=$_ARTIFACT_REGISTRY/$_IMAGE_NAME:$TAG_NAME-ubuntu",
- id: saveCache
  waitFor: ["buildSlimImage", "buildUbuntuImage"]
  name: gcr.io/$PROJECT_ID/save_cache:latest
  args:
  - "--bucket=gs://$_COMPILE_CACHE_BUCKET"
  - "--key=$_IMAGE_NAME-$_BRANCH_NAME"
  - "--path=.gradle/caches"
  - "--path=.gradle/wrapper"

tags: ["type_containers", "repo_$_IMAGE_NAME", "branch_$_BRANCH_TAG"]
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
substitutions:
  _COMPILE_CACHE_BUCKET: spinnaker-build-cache
  _BRANCH_TAG: unknown
  _ARTIFACT_REGISTRY: us-docker.pkg.dev/spinnaker-community/nightly
